### PR TITLE
Bootstrap js requires jQuery, improve readme

### PR DESCRIPTION
**Pull request by samarjeet27**
1. See http://getbootstrap.com/javascript/
Also, error message about this was appearing in the console

2. The README doesn't include information about
```sh
bower install
```
which installs angularjs, without which the apps is not functional

@eMBee

### CODE REVIEW

**Comment by eMBee** [comment]
actually, bootstrab is not used and should be removed (because it conflicts with other site design when embedded)
bower is configured to run automatically, so it doesn't need to be run manually. did that not happen for you?

**Comment by samarjeet27** [comment]
@eMBee, nope it didn't run automatically, I had to use bower install
Also, why don't you remove the link to bootstrap ?

**Comment by eMBee** [comment]
did you run npm install? it should call bower install...
as for removing bootstrap, i just didn't get around to it yet. feel free to submit a pull request for that instead.

**Comment by samarjeet27** [comment]
@eMBee will submit for removing bootstrap, but some elements will render differently

**Pull request closed without merging**
